### ISSUE TITLE
Inconsistent commit history

### ISSUE THREAD

**Issue by TristanCacqueray** [TristanCacqueray/dhall-ansible#6]
It seems like I messed up the merge, I did not realized GitHub would alter the author when doing the squash, and when doing rebase it did not used the top level comment.
IIUC I should have used the merge commit.

I would prefer to rewrite the history (using `push -f`) to preserve @GambolingPangolin author, but I'm ok to keep it as-is and I'll document that further PR needs to be merged using the merge commit.

**Comment by GambolingPangolin** [comment]
Did you already force push a new commit?  In my view, I _am_ the author of the most recent commit and you are the "committer".

**Comment by TristanCacqueray** [comment]
No I did not use force push yet, on the GitHub user interface you indeed appears as the author, but looking at the `git log` command output, I noticed GitHub replaced your mail with: `22924983+GambolingPangolin@users.noreply.github.com`.

I don't think it is a big deal, but I wanted to make a note and offer to rewrite the history.

**Comment by TristanCacqueray** [comment]
Next time I'll try to use the default merge commit option, which I think should preserve the author line.

**Comment by GambolingPangolin** [comment]
I configured Github to keep my email private, but am not careful about leaking it in commits.  I'm indifferent about which course of action you take so feel free to do what you think is best.

**Comment by TristanCacqueray** [comment]
Oh that must explain why github picked such mail address. Then if that's ok with you, I'll keep the history as is.

Thank you for the prompt feedback!
