### ISSUE TITLE
Request for "how to" example

### ISSUE THREAD

**Issue by hgolden** [TristanCacqueray/dhall-ansible#7]
Hi Tristan,

I really like the idea of dhall-ansible. Thanks for writing it!

I would like to use dhall-ansible to write my playbooks. Once I have done that, how to I run them? Do I first use a command to convert (all of) them to corresponding YAML files? Or is there a way I can simply put something at the start of the ansible command (playbook) that does this on the fly? I would appreciate a brief example of how you do things "end-to-end." Thanks!

Howard

**Comment by TristanCacqueray** [comment]
Hi @hgolden , thank you for the feedback!

Ansible doesn't read dhall natively and you have to convert the expression to YAML first. The simplest solution is to include a Makefile in your project that runs the `dhall-to-yaml` command for all your playbook / task files. We usually commit those files along the dhall expression and we have a CI job that ensure running make doesn't produce a diff.

Alternatively you can try https://github.com/timbertson/dhall-render/

**Comment by hgolden** [comment]
@TristanCacqueray , thank you for your explanation and the link to @timbertson 's dhall-render! I will try both.
